### ISSUE TITLE
Chrome 60+

### ISSUE THREAD

**Issue by fleamour** [diospiroverde/WazzApp#11]
Only works with Chrome 60+ & cannot load chat.

**Comment by diospiroverde** [comment]
Hi, 

Can you try this?

Menu Bar -> Session -> Clear Cache
Menu Bar-> Session -> Clear All Data

**Comment by fleamour** [comment]
Thx! Now working again...

**Comment by fleamour** [comment]
Persists after power cycle.

**Comment by diospiroverde** [comment]
Hi, fleamour.

Something changed at WhatsApp side, I'm seeing this problem with some other clients as well. I have published a "hotfix" for this. It is still possible the message may appear randomly, in that case just click refresh on the tray icon and you should be OK.

I'll be further investigating this and, if possible, publish a more permanent fix.

Please run

snap refresh wazzapp 

to update to version 0.3.0.

Please let me know if the fix worked for you.

All the best.

**Comment by fleamour** [comment]
Thx for your prompt response! Device shows as Chrome Linux under WhatsApp but unfortunately still same bug present & refresh no rectify.

**Comment by diospiroverde** [comment]
Can you please confirm you have version 0.3.0 in the about button?

If you have it, perhaps you could try uninstalling with

snap remove - - purge wazzap

And reinstall with

snap install wazzapp

I have it working on my side, but I will probably release another version later today.

**Comment by fleamour** [comment]
I'm missing a font, what font do you use?

**Comment by diospiroverde** [comment]
Hi,

I have corrected the syntax for further reference.

I have published version 0.3.1 that *should* work ok with whatsapp beta. I have tested it on my side and it's working fine. When I have the time I'll rewrite the app for a newer version of electron (will have to make changes because of context isolation).

Tomorrow I'll take a look at that font issue, this seems to be a bug with electron that I've read about before.

You may try deleting the app font chache. These are the directories in my system.

rm -f ~/snap/inkdrop/common/.cache/fontconfig/*
rm -f ~/snap/inkdrop/current/.cache/fontconfig/*

**Comment by fleamour** [comment]
Mad love Mr. Developer Sir! All quiet on the Western Front & fully functional so far!
